# Generated by Django 5.0 on 2024-02-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_photo', models.ImageField(upload_to='./photo_profile')),
            ],
        ),
    ]
