# Generated by Django 5.0 on 2024-02-05 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0002_profilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritearticle',
            name='user',
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='email',
            field=models.EmailField(default=12, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ModeratorArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elasticsearch_ids', models.JSONField(blank=True, default=list)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.moderateur')),
            ],
        ),
    ]
