# Generated by Django 5.0 on 2024-02-06 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0003_remove_favoritearticle_user_favoritearticle_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='moderateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='TP_IGL_app.moderateur'),
        ),
    ]
