# Generated by Django 5.0 on 2023-12-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0007_articleauteur_institutionauteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='article',
            name='moderateur',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='references',
        ),
        migrations.RemoveField(
            model_name='favoritearticle',
            name='articles',
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='article_ids',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='TP_IGL_app.article'),
        ),
        migrations.AlterField(
            model_name='favoritearticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
