# Generated by Django 5.0 on 2023-12-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0008_remove_article_admin_remove_article_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritearticle',
            name='article_ids',
        ),
        migrations.AddField(
            model_name='favoritearticle',
            name='elasticsearch_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
