# Generated by Django 5.0 on 2024-01-01 05:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0009_remove_favoritearticle_article_ids_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='admin',
            field=models.ForeignKey(default=datetime.datetime(2024, 1, 1, 5, 41, 42, 95193, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='auteurs',
            field=models.ManyToManyField(to='TP_IGL_app.auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 5, 43, 16, 672872, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='etat',
            field=models.ForeignKey(default=datetime.datetime(2024, 1, 1, 5, 43, 37, 620723, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.etat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='moderateur',
            field=models.ForeignKey(default=datetime.datetime(2024, 1, 1, 5, 43, 48, 153722, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.moderateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_url',
            field=models.URLField(default=datetime.datetime(2024, 1, 1, 5, 44, 2, 925437, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(default=datetime.datetime(2024, 1, 1, 5, 44, 13, 721608, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='admin_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='admin_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='moderateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='moderateur_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='moderateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='moderateur_user_permissions', to='auth.permission'),
        ),
    ]
