
# Generated by Django 5.0 on 2024-01-03 02:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0009_remove_favoritearticle_article_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moderateur',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='moderateur',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='moderateur',
            name='username',
        ),
        migrations.AddField(
            model_name='article',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='auteurs',
            field=models.ManyToManyField(to='TP_IGL_app.auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.etat'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='article',
            name='institution',
            field=models.ManyToManyField(to='TP_IGL_app.institution'),
        ),
 
         migrations.AddField(
            model_name='article',
            name='moderateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.moderateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_url',
            field=models.URLField(),
            preserve_default=False,
        ),
         migrations.AddField(
            model_name='article',
            name='references',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderateur',
            name='pseudo',
            field=models.CharField(max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='moderateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='moderateur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='moderateur',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
