# Generated by Django 5.0 on 2024-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0010_article_admin_article_auteurs_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
