# Generated by Django 5.0 on 2024-01-03 02:28

import django.utils.timezone
from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0011_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
