# Generated by Django 5.0 on 2024-01-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0011_alter_moderateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='moderateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TP_IGL_app.moderateur'),
        ),
    ]
