# Generated by Django 5.0 on 2024-01-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0012_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
    ]
