# Generated by Django 5.0 on 2024-01-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0012_alter_article_moderateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='moderateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TP_IGL_app.moderateur'),
            preserve_default=False,
        ),
    ]
