# Generated by Django 5.0 on 2024-01-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0013_alter_article_moderateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleauteur',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleauteur',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='favoritearticle',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleAuteur',
        ),
        migrations.DeleteModel(
            name='FavoriteArticle',
        ),
    ]
