# Generated by Django 5.0 on 2024-01-03 02:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app','0013_remove_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='new_date_field',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
