# Generated by Django 5.0 on 2024-01-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0015_userfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
