# Generated by Django 5.0 on 2024-01-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0017_alter_favoritearticle_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='article',
            name='moderateur',
        ),
    ]
