# Generated by Django 5.0 on 2024-01-04 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TP_IGL_app', '0018_alter_userfeedback_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFeedback',
        ),
    ]
